<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Vite Build Directory
    |--------------------------------------------------------------------------
    |
    | This is the directory where Vite will place the compiled assets. This
    | should match the `build.outDir` option in your Vite configuration file.
    | It is relative to the `public` directory.
    |
    */

    'build_directory' => env('VITE_BUILD_DIRECTORY', 'build'),

    /*
    |--------------------------------------------------------------------------
    | Vite Manifest Path
    |--------------------------------------------------------------------------
    |
    | The absolute path to the Vite manifest file. In production, Laravel uses
    | this manifest to resolve hashed asset filenames. This must point to the
    | manifest.json generated by `vite build` inside the public directory.
    |
    */

    'manifest_path' => env('VITE_MANIFEST_PATH', public_path('build/manifest.json')),

    /*
    |--------------------------------------------------------------------------
    | Vite Dev Server URL
    |--------------------------------------------------------------------------
    |
    | The URL of the Vite development server. This is only used in local
    | development when running `npm run dev`. In production this is ignored
    | and the compiled manifest is used instead.
    |
    */

    'dev_server_url' => env('VITE_DEV_SERVER_URL', 'http://localhost:5173'),

];
